// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RusMProject.Persistance.DbContexts;

namespace RusMProject.Persistance.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230201102847_Mi2023.02.01Third")]
    partial class Mi20230201Third
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RusMProject.Domain.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatorDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatorDate");

                    b.Property<int>("CreatorUserId")
                        .HasColumnType("int")
                        .HasColumnName("CreatorUserId");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EditorDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("EditorDate");

                    b.Property<int?>("EditorUserId")
                        .HasColumnType("int")
                        .HasColumnName("EditorUserId");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("RusMProject.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("BirthDate");

                    b.Property<DateTime>("CreatorDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatorDate");

                    b.Property<int>("CreatorUserId")
                        .HasColumnType("int")
                        .HasColumnName("CreatorUserId");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("DepartmentId");

                    b.Property<DateTime?>("EditorDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("EditorDate");

                    b.Property<int?>("EditorUserId")
                        .HasColumnType("int")
                        .HasColumnName("EditorUserId");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Surname");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("RusMProject.Domain.Entities.ExceptionNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatorDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatorDate");

                    b.Property<int>("CreatorUserId")
                        .HasColumnType("int")
                        .HasColumnName("CreatorUserId");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Description");

                    b.Property<DateTime?>("EditorDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("EditorDate");

                    b.Property<int?>("EditorUserId")
                        .HasColumnType("int")
                        .HasColumnName("EditorUserId");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("ExceptionNotifications");
                });

            modelBuilder.Entity("RusMProject.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatorDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatorDate");

                    b.Property<int>("CreatorUserId")
                        .HasColumnType("int")
                        .HasColumnName("CreatorUserId");

                    b.Property<DateTime?>("EditorDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("EditorDate");

                    b.Property<int?>("EditorUserId")
                        .HasColumnType("int")
                        .HasColumnName("EditorUserId");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Password");

                    b.Property<string>("Patronymic")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Patronymic");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("PhoneNumber");

                    b.Property<string>("SecretAnswer")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SecretAnswer");

                    b.Property<string>("SecretQuestion")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SecretQuestion");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Surname");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RusMProject.Domain.Entities.Employee", b =>
                {
                    b.HasOne("RusMProject.Domain.Entities.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("RusMProject.Domain.Entities.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
